### ISSUE TITLE
我想给它支持ssr的组件，是否可行。

### ISSUE THREAD

**Issue by LonelyFellas** [uiwjs/react-only-when#50]

**Comment by jaywcjlove** [comment]
@LonelyFellas  刚为你测试了一下 `Only` 是支持 ssr, `Switch` 在 `v2`支持了，v1 支持 ssr

**Comment by jaywcjlove** [comment]
@LonelyFellas 老的代码没有问题，但是有个问题 #45 ，里面使用了即将过时 API

![image](https://github.com/uiwjs/react-only-when/assets/1680273/7c387198-febf-431c-8edc-8a6f7563d5f5)

所以使用 Context 来解决这个问题，同时解决了，可以跨组件使用 `Switch`，`v1` 对子组件进行循环，进行判断，所以下面方式在 v2 中不出问题，在 v1 中 Case 就失效了

```jsx
<Switch>
    <div>
      <Case as="span" condition={age < 6}>Preschool</Case>
    </div>
</Switch>
```

**Comment by jaywcjlove** [comment]
@LonelyFellas 所以有没有解决 ssr 的方法呢？

createContext only works in Client Components. Add the "use client" directive at the top of the file to use it.

**Comment by jaywcjlove** [comment]
@LonelyFellas 你这个差不多是我  v1 版本的逻辑循环子节点，去处理

v2 版本的逻辑是，加载 `Case` 和 `Default` 的时候收集数据，存储到全局 context 里面，在渲染的时候，拿到数据进行判断

**Comment by jaywcjlove** [comment]
@LonelyFellas 代码逻辑更清晰简单，我发现我本地还有没有提交的代码 😄

**Comment by jaywcjlove** [comment]
@LonelyFellas 移除冗余代码之后，简单多了。现在可能不支持ssr 需要在文件上添加 "use client"

没有用到 `useState` 主要是 `createContext `

**Comment by jaywcjlove** [comment]
@LonelyFellas 根据你给的示例，我看了 v1 的代码，进行了重构，升级 `v3.0.0`

**Comment by jaywcjlove** [comment]
@LonelyFellas Upgrade `v3.0.1`
